apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-pod-demo
  labels:
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alpine
  template:
    metadata:
      labels:
        app: alpine
    spec:
      containers:
      - name: alpine-container
        image: gcr.io/google-containers/alpine-with-bash:1.0
        command: ["/bin/sh", "-c", "while true; do echo 'Alpine Container Running...'; sleep 3600; done"]
        resources:
          limits:
            cpu: "250m"
            memory: "128Mi"
          requests:
            cpu: "100m"
            memory: "64Mi"
