apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod-demo
  labels:
    app: myapp
spec:
#   imagePullSecrets:
#     - name: google
  containers:
    - name: deepakgc-gcr-image
      image: gcr.io/google-containers/alpine-with-bash:1.0
      imagePullPolicy: IfNotPresent
      command:
        - /bin/sh
        - "-c"
        - "sleep 70m"
        
