apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod-demo
  labels:
    app: myapp
spec:
  imagePullSecrets:
    - name: google
  containers:
    - name: deepakgc-gcr-image
      image: gcr.io/production-313223/kustomize-app:1.0.12
      
